# Generated by Django 5.1 on 2024-08-08 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_processing', 'в обработке'), ('confirmed', 'подтвержден'), ('canceled', 'отменен'), ('issued', 'выдан')], default='in_processing', max_length=20)),
                ('telephone', models.CharField(max_length=11)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
