# Generated by Django 5.1 on 2024-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('none', 'Без категории'), ('shawarma', 'Шаурма'), ('beer', 'Пивко')], default='none', max_length=10),
        ),
    ]
