# Generated by Django 5.0 on 2024-08-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavenlymenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
    ]
