# Generated by Django 5.0.8 on 2024-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='count')),
            ],
        ),
    ]
