# Generated by Django 5.1 on 2024-08-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('sort', models.CharField(max_length=200, verbose_name='Сорт')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
                ('alcohol', models.IntegerField(verbose_name='Крепость')),
                ('density', models.IntegerField(verbose_name='Плотность')),
                ('producer', models.CharField(max_length=200, verbose_name='Производитель')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Пиво',
                'verbose_name_plural': 'Пиво',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('measurement_unit', models.CharField(max_length=200, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество ингредиента')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент в шаурме',
                'verbose_name_plural': 'Ингредиенты в шаурме',
            },
        ),
        migrations.CreateModel(
            name='Shaurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('ingredients', models.ManyToManyField(through='stuff.Recipe', to='stuff.ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Шаурма',
                'verbose_name_plural': 'Шаурма',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='shaurma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.shaurma', verbose_name='Шаурма'),
        ),
    ]
