# Generated by Django 5.1 on 2024-08-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaurma',
            name='ingredients',
            field=models.ManyToManyField(related_name='shaurma', through='stuff.Recipe', to='stuff.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
