# Generated by Django 5.1 on 2024-08-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_alter_shaurma_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaurma',
            name='ingredients',
            field=models.ManyToManyField(through='stuff.Recipe', to='stuff.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
