# Generated by Django 5.1 on 2024-08-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_alter_shaurma_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shaurma',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
